### ISSUE TITLE
I'm not able to use ./replay_touch_events.sh

### ISSUE THREAD

**Issue by prasathyadhav** [Cartucho/android-touch-record-replay#25]
Can't execute ./mysendevent in device
LOGS:
/system/bin/sh: ./mysendevent: not executable: 64-bit ELF file

Device Details:
Poco f1
Android 10
MIUI 11.0.8.0

**Comment by prasathyadhav** [comment]
I edited the ./mysendevent.sh file to use the arm-64 binary.
I now get could not open /dev/input/event2, Permission denied

**Comment by prasathyadhav** [comment]
I'm sorry for the disturbance. I just found that we can't edit that particular file without root in android 10. I wish to contribute to this project to write an alternate python implementation for replay in android 10. Any ideas on how to get x , y values of swipe events, and long-press from the data hex.

**Comment by Cartucho** [comment]
Hello,

Yeah, they made this difficult for Android 10. I guess as they increase "the security" they will make it harder to do things like this.

Please let me know if you find any solution without rooting the phone.
