### ISSUE TITLE
Does not play back last touch

### ISSUE THREAD

**Issue by KonradStanski** [Cartucho/android-touch-record-replay#6]
I noticed while using this that when I play an event, if it a touch event for example, it will leave the touch pushed down. Maybe an indexing issue? Id appreciate some assistance in resolving this issue. This also has the effect that running a recorded swipe consecutively will chain the swipes together not moving the screen as when you next "touch" the screen, the swipe continues.

**Comment by Cartucho** [comment]
Hey, which Android version are you using? Android 9.0?

**Comment by Cartucho** [comment]
Please have a look at the following comment: 
https://github.com/Cartucho/android-touch-record-replay/issues/5#issuecomment-491913776

**Comment by Cartucho** [comment]
@KonradStanski, this should be fixed now
